# Group + Template combined, uses only core actions + http:backstage:request

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  namespace: default
  description: Platform Team
spec:
  type: team
  profile:
    displayName: Platform Team
  children: []
---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: repo-to-vercel-project
  namespace: default
  title: Link existing GitHub repo to Vercel
  description: Creates a Vercel Project from an existing GitHub repository
spec:
  owner: group:default/platform-team
  type: service

  parameters:
    - title: Git and Vercel
      required:
        - githubRepo
        - projectName
      properties:
        githubRepo:
          title: GitHub repo (owner/name)
          type: string
          description: Example vercel/next.js
        projectName:
          title: Vercel project name
          type: string
          description: Will be the project slug in Vercel
        vercelTeamId:
          title: Vercel teamId (optional)
          type: string
          description: Example team_abc123. Leave empty for personal scope

  steps:
    - id: create-vercel-project
      name: Create Vercel Project
      action: http:backstage:request
      input:
        method: POST
        path: >-
          proxy/vercel/v11/projects${{ parameters.vercelTeamId && ('?teamId=' + parameters.vercelTeamId) || '' }}
        headers:
          Content-Type: application/json
        body:
          name: ${{ parameters.projectName }}
          framework: nextjs
          gitRepository:
            type: github
            repo: ${{ parameters.githubRepo }}
            sourceless: true

  output:
    text:
      - title: Vercel project created
        content: >-
          Project "${{ parameters.projectName }}" has been created in Vercel
          and linked to GitHub repo "${{ parameters.githubRepo }}".
